# Generated by Django 4.1.2 on 2022-10-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='is_done',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='owner_user',
        ),
    ]
